<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-0J3EE46" failures="1" tests="1" name="OrangeHRM.Cucumber.Runners.RegressionTestRunner" time="16.535" errors="0" timestamp="2025-02-23T10:46:36 IST" skipped="0">
  <testcase classname="OrangeHRM.Cucumber.Runners.RegressionTestRunner" name="runScenario" time="16.535">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at OrangeHRM.Cucumber.StepDefinitions.PIMSteps.i_should_see_a_confirmation_message(PIMSteps.java:55)
at âœ½.I should see a confirmation message "Successfully SaveD"(file:///C:/Users/DELL/eclipse-workspace/ORANGE-HRM-Java-Selenium/src/test/java/OrangeHRM/Cucumber/Features/PIM.feature:15)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- OrangeHRM.Cucumber.Runners.RegressionTestRunner -->
